name: WF Sample

on: [workflow_dispatch]

jobs:
  job1:
    name: first job to run
    runs-on: ubuntu-latest
    env:
      MY_ENV: This is the value of my env var
    steps:
      - name: List_job
        run: echo '${{toJSON(job)}}'
      - name: List_runner
        run: echo '${{toJSON(runner)}}'
      - name: List_EW
        run: echo '${{toJSON(env)}}'
      - name: List_github
        run: echo '${{toJSON(github)}}'
